### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by auchers** [UrbanSystemsLab/data-pipeline-newYork#1]
[Wiki Datasets page](https://github.com/UrbanSystemsLab/data-pipeline-newYork/wiki/Datasets) -- at "importing attributes from lots to buildings” (towards the bottom)

[README](https://github.com/UrbanSystemsLab/data-pipeline-newYork) --  at "spatial-merge” (towards the bottom)

[USL dataviz page](http://urbansystemslab.com/dataviz/) -- at the "here" clickthrough to NY interactive visualization (just has a '.' at the end of the url).

**Comment by jaskiratr** [comment]
Fixed
